# Generated by Django 4.0.6 on 2022-07-20 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_alter_comments_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='parent_comment_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='watch.comments'),
        ),
    ]
