# Generated by Django 4.0.6 on 2022-07-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0004_alter_user_data_profile_image'),
        ('watch', '0006_comments_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_authentication.user_data'),
        ),
    ]
