# Generated by Django 4.0.6 on 2022-07-15 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_alter_user_data_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='thumbnail_image_url',
            new_name='profile_image',
        ),
        migrations.RenameField(
            model_name='user_data',
            old_name='user_id',
            new_name='username',
        ),
    ]
