# Generated by Django 4.0.6 on 2022-07-16 07:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0003_rename_thumbnail_image_url_user_data_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
