# Generated by Django 4.0.6 on 2022-07-17 16:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image2'),
        ),
    ]
