# Generated by Django 4.0.6 on 2022-07-17 20:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_alter_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='channel',
        ),
        migrations.AddField(
            model_name='video',
            name='channel_id',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video_link',
            field=cloudinary.models.CloudinaryField(default='def', max_length=255, verbose_name='Video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
