# Generated by Django 4.0.6 on 2022-07-17 21:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_alter_video_channel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='video_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Thumbnail')),
                ('video_link', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Video')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('channel_id', models.CharField(max_length=40)),
                ('video_views', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='video',
        ),
    ]
